    1.

------

In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import math 

In [2]:
iris = load_iris()

In [3]:
# Get the first 34 values of each line and label those as the values
ionoValues = np.genfromtxt("ionosphere.txt", delimiter=",",usecols=np.arange(34))

In [4]:
# Get the last value from each line and desginate it as the label of each value
ionoLabels = np.genfromtxt("ionosphere.txt", delimiter=",", usecols=34, dtype='int')

In [5]:
print(ionoLabels)

[ 1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1
  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1
  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1
  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1
  1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1

In [6]:
print(ionoLabels.shape)

(351,)


In [7]:
print(ionoValues)

[[ 1.       0.       0.99539 ... -0.54487  0.18641 -0.453  ]
 [ 1.       0.       1.      ... -0.06288 -0.13738 -0.02447]
 [ 1.       0.       1.      ... -0.2418   0.56045 -0.38238]
 ...
 [ 1.       0.       0.94701 ...  0.00442  0.92697 -0.00577]
 [ 1.       0.       0.90608 ... -0.03757  0.87403 -0.16243]
 [ 1.       0.       0.8471  ... -0.06678  0.85764 -0.06151]]


In [8]:
print(ionoValues.shape)

(351, 34)


    2.

-----

In [9]:
irisX_train, irisX_test, irisY_train, irisY_test = train_test_split(iris['data'], iris['target'], random_state=2309)

In [10]:
print(irisX_train.shape,irisX_test.shape)

(112, 4) (38, 4)


In [11]:
ionoX_train, ionoX_test, ionoY_train, ionoY_test = train_test_split(ionoValues, ionoLabels, random_state=2309)

In [12]:
print(ionoX_train.shape, ionoX_test.shape)

(263, 34) (88, 34)


    3. 

-----

In [13]:
def distanceBetweenPoints(vector1, vector2):
    'This function calculates/returns the distance between two vectors: vector1 and vector2'
    # Subtracting the two given vectors
        
    uv = np.subtract(vector1,vector2)

    # Finding the dot product of the 2
        
    total = np.dot(uv,uv)

    #Returning the distance between the 2 vectors
    
    return np.sqrt(total)

In [14]:
x = np.array([5, 2.9, 1, 0.2])

y = np.array([2, 1.3, 9, 4])

In [15]:
print(distanceBetweenPoints(x,y))

9.486832980505138


In [16]:
def nearestNeighbour(trainingSetValues, trainingSetLabels, valueToTest):
    'This function calculates/returns the label of 1 Nearest Neighbour given: a Training dataset, its corresponding label and the value to predict a label'


    # Set the current nearest label to be 0
    nearestLabel = 0
    
    # Set the current least distance to be infinite
    leastDistance = math.inf 
    
    # For every value in the training set
    for i in range(0,trainingSetValues.shape[0]):

        # Calculate the distance between the given training set value and the value to test
        distanceBetween = distanceBetweenPoints(trainingSetValues[i], valueToTest)
    
        # If the distance calculated is less than the leastDistance then update the distance and the labels
        if distanceBetween < leastDistance:
            leastDistance = distanceBetween
            nearestLabel = trainingSetLabels[i]
    
    return nearestLabel


In [17]:
def calculateSuccessRate (trainingSetValues, trainingSetLabels, testSetValues, testSetLabels):
    'This function calculates the error rate of the 1 Nearest Neighbours algorithm, given: The Training Dataset, its corresponding labels, dataset to test, corresponding labels to test data'

    # Counter variable to count the mistakes made by the program
    errorCount = 0

    predictedLabels =[]

    # For every value in the test set
    for i in range(0, len(testSetValues)):
       
       # Append the predicted labels to the new array
       predictedLabels.append(nearestNeighbour(trainingSetValues,trainingSetLabels, testSetValues[i]))

       print("Predicted Label: ", predictedLabels[i])
       print("Actual Label: ", testSetLabels[i])
       print(" ")
        
       # If the predicted does not match the correct one, add 1 to the error counter
       if predictedLabels[i] != testSetLabels[i]:
           errorCount +=1

    # Returns the Success rate in percentage
    return ((1- (errorCount/testSetLabels.shape[0])) * 100)

def calculateErrorRate(successRate):
    # Returns the error rate in percentage
    return 100 - successRate

In [18]:
successIono = calculateSuccessRate(ionoX_train,ionoY_train, ionoX_test, ionoY_test)

Predicted Label:  1
Actual Label:  -1
 
Predicted Label:  1
Actual Label:  -1
 
Predicted Label:  -1
Actual Label:  -1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  -1
 
Predicted Label:  -1
Actual Label:  -1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  -1
 
Predicted Label:  -1
Actual Label:  -1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  -1
Actual Label:  -1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  -1
Actual Label:  -1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted L

In [19]:
successIris = calculateSuccessRate(irisX_train,irisY_train, irisX_test,irisY_test)

Predicted Label:  0
Actual Label:  0
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  2
Actual Label:  2
 
Predicted Label:  2
Actual Label:  2
 
Predicted Label:  2
Actual Label:  2
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  2
Actual Label:  2
 
Predicted Label:  2
Actual Label:  1
 
Predicted Label:  2
Actual Label:  2
 
Predicted Label:  1
Actual Label:  2
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  0
Actua

In [20]:
print("Error rate for 1 NN for Ionosphere =", str(calculateErrorRate(successIono))+ "%")

Error rate for 1 NN for Ionosphere = 12.5%


In [21]:
print("Success rate for 1 NN for Ionosphere =", str(successIono)+ "%")

Success rate for 1 NN for Ionosphere = 87.5%


In [22]:
print("Error rate for 1 NN for Iris =", str(calculateErrorRate(successIris))+ "%")

Error rate for 1 NN for Iris = 7.89473684210526%


In [23]:
print("Success rate for 1 NN for Iris =", str(successIris) + "%")

Success rate for 1 NN for Iris = 92.10526315789474%


    3 (Nearest Neighbour N).

-----

In [24]:
def neighboursWithN(trainingSetValues, trainingSetLabels, valueToTest, numberOfNeighbours):
    'This function calculates N Nearest Neighbours labels, given: The Training Dataset, its corresponding labels, value to test, number of neighbours wanted'

    nearestNeighbors = {}  # A dictionary to store nearest neighbors and distances

    # For every value in the training data set
    for i in range(trainingSetValues.shape[0]):

        # Calculate the distance between the training set value and the value we are testing
        distanceBetween = distanceBetweenPoints(trainingSetValues[i], valueToTest)

        # Check length of the dictionary to see if it is less than the number of NN wanted to add to dictionary
        # And checks if the current distance is smaller than the largest distance in the neighbors (max size in array is 4)
        if len(nearestNeighbors) < numberOfNeighbours or distanceBetween < max(nearestNeighbors.values()):

            # If it is, add this new distance to the dictionary
            nearestNeighbors[i] = distanceBetween

        # If the length of the dictionary is greater than the number of Nearest Neighbours
        if len(nearestNeighbors) > numberOfNeighbours:

            # Get the largest distance found in the dictionary
            farthest_neighbor = max(nearestNeighbors, key=nearestNeighbors.get)

            # Delete the furthest neighbour from the dictionary
            del nearestNeighbors[farthest_neighbor]



    # Get the labels of the nearest neighbors based on the i-th value stored in the dictionary
    # It will iterate through all the labels till the i-th labels are reached according to the dictionary keys
    nearestLabels = [trainingSetLabels[n] for n in nearestNeighbors.keys()]

    # Returns the array of all the nearest labels
    return nearestLabels

In [25]:
def nearestNeighbourN(trainingSetValues, trainingSetLabels, valueToTest, numberOfNeighbours):
    'This function calculates N Nearest Neighbours predicted label, given: The Training Dataset, its corresponding labels, value to test, number of neighbours wanted'

    # Get all the nearest neighbours' labels
    nearest_labels = neighboursWithN(trainingSetValues, trainingSetLabels, valueToTest, numberOfNeighbours)

    # Create a dictionary with "Label: Number of occurences in array"
    label_counts = {label: nearest_labels.count(label) for label in set(nearest_labels)}   
     
    # Returns the key with the max value in the dictionary
        # list(label_counts.keys()) = Gets the all the labels from the dictionary
        # list(label_counts.values()) = Gets the values from those keys
        # .index(max(label_counts.values())) = Gets the index value of the max item
     
    return list(label_counts.keys())[list(label_counts.values()).index(max(label_counts.values()))]


In [26]:
def calculateSuccessRateWithN(trainingSetValues, trainingSetLabels, testSetValues, testSetLabels, numberOfNeighbours):

    errorCount = 0
    predictedLabels =[]

    for i in range(0, len(testSetValues)):
       predictedLabels.append(nearestNeighbourN(trainingSetValues,trainingSetLabels, testSetValues[i],numberOfNeighbours))

       print("Predicted Label: ", predictedLabels[i])
       print("Actual Label: ", testSetLabels[i])
       print(" ")

       if predictedLabels[i] != testSetLabels[i]:
           errorCount +=1

    return ((1- (errorCount/testSetLabels.shape[0])) * 100)


In [27]:
successIono3NN = calculateSuccessRateWithN(ionoX_train,ionoY_train, ionoX_test, ionoY_test,3)

Predicted Label:  1
Actual Label:  -1
 
Predicted Label:  1
Actual Label:  -1
 
Predicted Label:  -1
Actual Label:  -1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  -1
 
Predicted Label:  -1
Actual Label:  -1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  -1
 
Predicted Label:  -1
Actual Label:  -1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  -1
Actual Label:  -1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  -1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted La

In [28]:
successIris3NN = calculateSuccessRateWithN(irisX_train,irisY_train, irisX_test,irisY_test,3)

Predicted Label:  0
Actual Label:  0
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  2
Actual Label:  2
 
Predicted Label:  2
Actual Label:  2
 
Predicted Label:  2
Actual Label:  2
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  2
Actual Label:  2
 
Predicted Label:  2
Actual Label:  1
 
Predicted Label:  2
Actual Label:  2
 
Predicted Label:  1
Actual Label:  2
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  1
Actual Label:  1
 
Predicted Label:  0
Actual Label:  0
 
Predicted Label:  0
Actua

In [29]:
print("Success rate for 3 NN Iris =", str(successIris3NN)+ "%")

Success rate for 3 NN Iris = 92.10526315789474%


In [30]:
print("Success rate for 3 NN Ionosphere =", str(successIono3NN)+ "%")

Success rate for 3 NN Ionosphere = 86.36363636363636%


In [31]:
print("Error rate for 3 NN Iris =", str(calculateErrorRate(successIris3NN))+ "%")

Error rate for 3 NN Iris = 7.89473684210526%


In [32]:
print("Error rate for 3 NN Ionosphere =", str(calculateErrorRate(successIono3NN))+ "%")

Error rate for 3 NN Ionosphere = 13.63636363636364%


    4.

-----

In [33]:
def nonConformityMeasure(trainingSetValues, trainingSetLabels, testValue, predictedLabel):
    nearestSameLabelD = math.inf
    nearestOtherLabelD = math.inf

    # For every item in the dataset
    for i in range(trainingSetValues.shape[0]):

        # Checks that the testValue and the training set values are not the same
        if np.array_equal(trainingSetValues[i], testValue):
            continue

        # Calculate the distance between the current item and the item to test
        distanceBetween = distanceBetweenPoints(trainingSetValues[i], testValue)

        
        # Checks if the current trainingValue has the same label as the testValue and the distance is less than previously calculated
        if trainingSetLabels[i] == predictedLabel and distanceBetween < nearestSameLabelD:
            nearestSameLabelD = distanceBetween

        # Checks if the current trainingValue does not have the same label as the testValue and the distance is less than previously calculated
        if trainingSetLabels[i] != predictedLabel and distanceBetween < nearestOtherLabelD:
            nearestOtherLabelD = distanceBetween
            

    # Returns the non-conformity value from the equation:
        # the distance to the nearest sample of a different class/ the distance to the nearest sample of the same class
    return nearestOtherLabelD/nearestSameLabelD


In [34]:
print(irisX_train[0])

[5.1 3.3 1.7 0.5]


In [35]:
print(irisY_train[0])

0


In [36]:
# Calculating actual conformity score with true label
print(nonConformityMeasure(irisX_train,irisY_train, irisX_train[0], irisY_train[0]))

6.199078272499182


In [37]:
# Calculating actual conformity score with false label
print(nonConformityMeasure(irisX_train,irisY_train, irisX_train[0], irisY_train[1]))

0.0838338383339281


In [38]:
# Calculating actual conformity score with false label
print(nonConformityMeasure(irisX_train,irisY_train, irisX_train[0], irisY_train[10]))

0.16131430448882622


In [39]:
def nonConformityMeasureArray(trainingSetValues, trainingSetLabels):
    'This function, given a Training Set Values and Labels, returns an array of all non-conformity scores of each training value'
    nonConformityValues =[]
    
    for i in range(0,trainingSetValues.shape[0]):
        nonConformityValues.append(nonConformityMeasure(trainingSetValues, trainingSetLabels, trainingSetValues[i], trainingSetLabels[i]))

    return nonConformityValues

In [40]:
print(nonConformityMeasureArray(irisX_train,irisY_train))

[6.199078272499182, 2.2267315359812323, 2.6457513110645854, 1.8973665961010249, 1.4719601443879755, 2.2360679774997894, 6.462911941936913, 1.7320508075688759, 3.937003937005917, 3.6689969285267146, 6.3639610306789205, 2.9760952365713798, 2.9769227342202287, 6.359594676112968, 8.06225774829854, 6.59545297913644, 5.555505050275485, 8.567379996241574, 4.499999999999995, 1.9663841605003505, 4.415880433163935, 3.7859388972001806, 7.745966692414826, 9.528903399657278, 7.8102496759066655, 3.2403703492039275, 15.508062419270852, 6.964194138592057, 13.52774925846867, 8.660254037844396, 8.62167810425171, 9.230384607371471, 3.291402943021915, 8.602325267042618, 12.30176139149731, 3.2403703492039213, 10.53565375285273, 6.78232998312527, 4.222953153106638, 8.346656017032613, 13.152946437965893, 2.4083189157584632, 3.511884584284245, 2.701851217221262, 1.4392458342578487, 14.335271186831438, 2.1679483388678804, 0.9636241116594312, 14.474114826130117, 2.260776661041754, 10.816653826391956, 1.40054934

In [41]:
def nonConformalPrediction(trainingSetValues, trainingSetLabels, testValue):
    'This function, given the Training set values and corresponding labels as well as a value to test will return the non-conformal values for all the values'
    scores =[] 
    
    # Here I am creating a copy of the original training set as I will append the test value and all the new labels to test, iteratively to the test trainingSet
    originalTrainingSet = np.copy(trainingSetValues)
    originalTrainingSetLabels = np.copy(trainingSetLabels)


    # Adding the new value to test to the training set and changing the shape to accomodate the new value
    trainingSetValues = np.append(trainingSetValues, testValue)
    trainingSetValues = np.reshape(trainingSetValues,(originalTrainingSet.shape[0]+1,originalTrainingSet.shape[1]))

    # Count the number of labels in this training set 
    labelsToUse = countLabels(trainingSetLabels)

    # For every label, add that new testValue and a given label and calculate the non-conformity value
    # Add score to an array, clean the trainingSetLabels and move to the next label
    for i in range(0, len(labelsToUse)):
    
        trainingSetLabels = np.append(trainingSetLabels, labelsToUse.pop())    
        conformityArray = nonConformityMeasureArray(trainingSetValues, trainingSetLabels)
        scores.append(conformityArray)
        trainingSetLabels = np.copy(originalTrainingSetLabels)


    # Revert the datasets to what they were previously
    trainingSetValues = np.copy(originalTrainingSet)
    trainingSetLabels = np.copy(originalTrainingSetLabels)

    # Return an array of arrays with n dimensions where N is the number of labels
    return scores



def countLabels(trainingSetLabels):
    'This function, given a set of labels, will produce a set containing all the distinct labels'
    setLabels = set()

    for x in range(len(trainingSetLabels)-1):
        setLabels.add(trainingSetLabels[x])

    return setLabels



In [42]:
def calculatePValue(trainingSetValues, trainingSetLabels, testValue, testLabel):
    'This function, given the training set values and labels, and a test value and its label, will calculate the P value for each data entry'
    pValues = []

    # Get the conformity scores arrays
        # Arrays will be conformalArrays[0] = First Label Conformity Values
    conformalArrays = nonConformalPrediction(trainingSetValues,trainingSetLabels, testValue)

    labels = countLabels(trainingSetLabels)

    for i in range(len(labels)):

        # Setting count to 1 as lowest p(y) is 1/number of values, not 0/number of values
        count = 1

        # Produce a rank for each value based on their conformity score
        sortedArray = np.array(conformalArrays[i]).argsort()

        # This for loop will calculate the rank of the value based on their position in the sortedArray
        for x in range(len(sortedArray)):

            # If value found
            if sortedArray[x] == len(conformalArrays[i])-1:
                break

            # Add 1 to counter
            else:
                count = count + 1
        

        # Calculating the P value
        pValue = (count/len(sortedArray))

        currentLabel = labels.pop()

        # This if statement, makes sure that the correct Label gives a higher P value
            # This is because the wrong label may give a higher P value but we want to make sure that we count the false P values
        if testLabel == currentLabel:
            pValues.append(pValue +1)

        else:
            pValues.append(pValue)

        print("P Value for ", testValue, " and label ", currentLabel, " is: ",pValue)


    return pValues


In [43]:
calculatePValue(irisX_train,irisY_train, irisX_test[2],irisY_test[2])

P Value for  [5.5 4.2 1.4 0.2]  and label  0  is:  0.7433628318584071
P Value for  [5.5 4.2 1.4 0.2]  and label  1  is:  0.008849557522123894
P Value for  [5.5 4.2 1.4 0.2]  and label  2  is:  0.008849557522123894


[1.7433628318584071, 0.008849557522123894, 0.008849557522123894]

In [44]:
def calculateAvgFalseP(trainingSetValues, trainingSetLabels, testSetValues, testSetLabels):
    'This function, given the training set values and labels, the test values and their labels, will calculate average false P value for the datasets'
    falsePValues= []

    for i in range(0, testSetValues.shape[0]):

        # Calculates the P value for a given value and label
        pValues = calculatePValue(trainingSetValues, trainingSetLabels, testSetValues[i],testSetLabels[i])
        print(" ")
        
        # Removes the max value, i.e the correct label P value
        maxP = max(pValues)
        pValues.remove(maxP)

        # Appends the false values to an array
        falsePValues.append(pValues)

    cumSum = 0
    counter = 0

    # For every value in the false P values array, sum all the values 
    for x in range(len(falsePValues)):
        for z in range(len(falsePValues[x])):
            cumSum =  cumSum + falsePValues[x][z]
            counter = counter + 1

    # Return average false P-Value
    return cumSum/counter

In [45]:
print("The Average False P-Value of Iris is: " ,calculateAvgFalseP(irisX_train,irisY_train, irisX_test,irisY_test))

P Value for  [5.  3.4 1.6 0.4]  and label  0  is:  0.8230088495575221
P Value for  [5.  3.4 1.6 0.4]  and label  1  is:  0.008849557522123894
P Value for  [5.  3.4 1.6 0.4]  and label  2  is:  0.008849557522123894
 
P Value for  [7.  3.2 4.7 1.4]  and label  0  is:  0.008849557522123894
P Value for  [7.  3.2 4.7 1.4]  and label  1  is:  0.46017699115044247
P Value for  [7.  3.2 4.7 1.4]  and label  2  is:  0.008849557522123894
 
P Value for  [5.5 4.2 1.4 0.2]  and label  0  is:  0.7433628318584071
P Value for  [5.5 4.2 1.4 0.2]  and label  1  is:  0.008849557522123894
P Value for  [5.5 4.2 1.4 0.2]  and label  2  is:  0.008849557522123894
 
P Value for  [4.8 3.4 1.9 0.2]  and label  0  is:  0.6460176991150443
P Value for  [4.8 3.4 1.9 0.2]  and label  1  is:  0.008849557522123894
P Value for  [4.8 3.4 1.9 0.2]  and label  2  is:  0.008849557522123894
 
P Value for  [5.  3.2 1.2 0.2]  and label  0  is:  0.7433628318584071
P Value for  [5.  3.2 1.2 0.2]  and label  1  is:  0.008849557522

In [46]:
print("The Average False P-Value of Iono is: " ,calculateAvgFalseP(ionoX_train,ionoY_train, ionoX_test,ionoY_test))

P Value for  [ 1.       0.       1.      -0.05529  1.      -1.       0.5     -0.11111
  0.36111 -0.22222  1.      -0.25712  0.16667 -0.11111  1.      -0.3466
  1.      -0.38853  1.      -0.42862  0.      -0.25     1.      -0.50333
  1.      -0.27778  1.      -0.57092  1.      -0.27778  1.      -0.63156
  1.      -0.65935]  and label  1  is:  0.36363636363636365
P Value for  [ 1.       0.       1.      -0.05529  1.      -1.       0.5     -0.11111
  0.36111 -0.22222  1.      -0.25712  0.16667 -0.11111  1.      -0.3466
  1.      -0.38853  1.      -0.42862  0.      -0.25     1.      -0.50333
  1.      -0.27778  1.      -0.57092  1.      -0.27778  1.      -0.63156
  1.      -0.65935]  and label  -1  is:  0.03787878787878788
 
P Value for  [ 1.       0.       0.43636 -0.12727  0.58182 -0.14545  0.18182 -0.67273
  0.34545 -0.03636  0.29091 -0.05455  0.29091  0.29091  0.36364 -0.41818
  0.2     -0.01818  0.36364  0.05455  0.12727  0.49091  0.61818  0.16364
  0.32727  0.16364  0.41098 -0.07027 